### ISSUE TITLE
Can't build on Windows if a module is declared with forward slashes

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/documentjs#208] opened 2015-09-29 00:16 UTC
I get the following error when building on Windows (using master):

```
Warning: ENOENT, open 'C:\path\to\repo\docs\components|thingy|.html' Use --force to continue.
```

The module `thingy` is declared as:

```
@module {function} components/thingy Thingy
```

If I change it to a backward slash, it builds fine.

**Comment by justinbmeyer** [comment] 2015-09-29 00:20
A duplicate of #104, which is the right solution for this.

**Comment by justinbmeyer** [comment] 2015-09-29 00:20
https://github.com/bitovi/documentjs/issues/104

**Closed by justinbmeyer** 2015-09-29 00:20 UTC
